# Replace with your created tunnel ID and creds file path
tunnel: YOUR_TUNNEL_ID
credentials-file: /root/.cloudflared/YOUR_TUNNEL_ID.json

ingress:
  - hostname: wallykroeker.com
    service: http://127.0.0.1:3000
  - hostname: www.wallykroeker.com
    service: http://127.0.0.1:3000
  - service: http_status:404
