#!/usr/bin/env bash
# add-pebble-episode.sh — Add a new Pebble Weekend episode and regenerate the RSS feed.
#
# Usage (run from your dev machine or directly on the production server):
#   ./scripts/add-pebble-episode.sh /path/to/2026-08-17-pebble-weekend.mp3 "Aug 15-17, 2026"
#
# The /public/pf/ directory is gitignored. This script manages it on the TARGET server.
# To run against production: ssh to the prod box, then run from /home/docker/wallykroeker.com/.
# Or use the --remote flag to run via SSH (requires PROD_HOST env var):
#   PROD_HOST=user@server ./scripts/add-pebble-episode.sh ep.mp3 "Aug 15-17, 2026" --remote

set -euo pipefail

FEED_TOKEN="380726eef96340aba9ab44df45e852d3"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
FEED_DIR="${REPO_ROOT}/public/pf/${FEED_TOKEN}"
EPISODES_DIR="${FEED_DIR}/episodes"
FEED_FILE="${FEED_DIR}/feed.xml"
BASE_URL="https://wallykroeker.com/pf/${FEED_TOKEN}"

MP3_SOURCE="${1:-}"
EPISODE_LABEL="${2:-}"
REMOTE_FLAG="${3:-}"

if [[ -z "$MP3_SOURCE" || -z "$EPISODE_LABEL" ]]; then
  echo "Usage: $0 /path/to/YYYY-MM-DD-pebble-weekend.mp3 \"Month DD-DD, YYYY\" [--remote]"
  echo "Example: $0 ~/projects/TSFUR/audio/2026-08-17-pebble-weekend.mp3 \"Aug 15-17, 2026\""
  exit 1
fi

if [[ ! -f "$MP3_SOURCE" ]]; then
  echo "Error: file not found: $MP3_SOURCE"
  exit 1
fi

MP3_BASENAME="$(basename "$MP3_SOURCE")"
EPISODE_DATE="$(echo "$MP3_BASENAME" | grep -oP '^\d{4}-\d{2}-\d{2}' || true)"
if [[ -z "$EPISODE_DATE" ]]; then
  echo "Error: filename must start with YYYY-MM-DD (got: $MP3_BASENAME)"
  exit 1
fi

# Ensure directories exist
mkdir -p "${EPISODES_DIR}"

# Copy the episode file
cp "$MP3_SOURCE" "${EPISODES_DIR}/${MP3_BASENAME}"
echo "Copied: ${MP3_BASENAME}"

# Get file size in bytes
BYTE_LENGTH=$(stat -c%s "${EPISODES_DIR}/${MP3_BASENAME}")

# Build pubDate (Sun, 10 Aug 2026 12:00:00 -0500)
PUB_DATE=$(date -d "${EPISODE_DATE}" '+%a, %d %b %Y 12:00:00 -0500' 2>/dev/null || \
           date -j -f "%Y-%m-%d" "${EPISODE_DATE}" '+%a, %d %b %Y 12:00:00 -0500')

# New <item> block to prepend
NEW_ITEM="    <item>
      <title>Pebble Weekend \xe2\x80\x94 ${EPISODE_LABEL}</title>
      <description>Weekly digest for ${EPISODE_LABEL}. Generated by Bob from pebble-daily notes.</description>
      <pubDate>${PUB_DATE}</pubDate>
      <guid isPermaLink=\"false\">pebble-weekend-${EPISODE_DATE}</guid>
      <enclosure
        url=\"${BASE_URL}/episodes/${MP3_BASENAME}\"
        length=\"${BYTE_LENGTH}\"
        type=\"audio/mpeg\"/>
      <itunes:duration>0:00</itunes:duration>
      <itunes:explicit>no</itunes:explicit>
    </item>"

if [[ ! -f "$FEED_FILE" ]]; then
  # Bootstrap the feed from scratch
  cat > "$FEED_FILE" <<FEEDEOF
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"
  xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd"
  xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Pebble Weekend</title>
    <description>Wally's private weekly digest -- context, reflection, and what's on the board.</description>
    <link>https://wallykroeker.com</link>
    <language>en-ca</language>
    <copyright>Private -- not for distribution</copyright>
    <itunes:author>Bob</itunes:author>
    <itunes:explicit>no</itunes:explicit>
    <itunes:category text="Personal Journals"/>
    <atom:link href="${BASE_URL}/feed.xml" rel="self" type="application/rss+xml"/>

${NEW_ITEM}

  </channel>
</rss>
FEEDEOF
  echo "Feed created from scratch: ${FEED_FILE}"
else
  # Prepend the new item before the first existing <item>
  python3 - <<PYEOF
import re

new_item = """${NEW_ITEM}"""

with open("${FEED_FILE}", "r", encoding="utf-8") as f:
    content = f.read()

# Insert before first <item> block, or before </channel>
if "<item>" in content:
    content = content.replace("<item>", new_item + "\n\n    <item>", 1)
else:
    content = content.replace("  </channel>", "\n" + new_item + "\n\n  </channel>")

with open("${FEED_FILE}", "w", encoding="utf-8") as f:
    f.write(content)
print("Feed updated.")
PYEOF
fi

# Regenerate index.html from feed.xml (newest-first player page)
INDEX_FILE="${FEED_DIR}/index.html"
python3 - <<PYEOF
import xml.etree.ElementTree as ET

tree = ET.parse("${FEED_FILE}")
ns = {"itunes": "http://www.itunes.com/dtds/podcast-1.0.dtd"}
items = tree.findall(".//item")

episode_blocks = ""
for item in items:
    title = item.findtext("title", "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    pub_date = item.findtext("pubDate", "")
    duration_el = item.find("itunes:duration", ns)
    duration = duration_el.text if duration_el is not None else ""
    enc = item.find("enclosure")
    url = enc.get("url", "") if enc is not None else ""
    # Relative URL for local serving (strip base URL prefix)
    rel_url = url.replace("https://wallykroeker.com/pf/${FEED_TOKEN}/", "")
    meta_parts = [p for p in [pub_date.split(" 12:")[0] if pub_date else "", duration] if p]
    meta = " &bull; ".join(meta_parts)
    episode_blocks += f"""
    <article class="episode">
      <div class="episode-title">{title}</div>
      <div class="episode-meta">{meta}</div>
      <audio controls preload="metadata">
        <source src="{rel_url}" type="audio/mpeg">
        Your browser does not support the audio element.
      </audio>
    </article>
"""

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="robots" content="noindex, nofollow">
  <title>Pebble Weekend</title>
  <style>
    *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}

    body {{
      background: #111;
      color: #d4d4d4;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      font-size: 16px;
      line-height: 1.6;
      padding: 2rem 1rem;
      max-width: 640px;
      margin: 0 auto;
    }}

    header {{
      border-bottom: 1px solid #333;
      padding-bottom: 1.25rem;
      margin-bottom: 2rem;
    }}

    header h1 {{
      font-size: 1.25rem;
      font-weight: 600;
      color: #f0f0f0;
    }}

    header p {{
      font-size: 0.85rem;
      color: #666;
      margin-top: 0.25rem;
    }}

    .episode {{
      border: 1px solid #222;
      border-radius: 6px;
      padding: 1.25rem;
      margin-bottom: 1.25rem;
      background: #161616;
    }}

    .episode-title {{
      font-size: 1rem;
      font-weight: 600;
      color: #e8e8e8;
      margin-bottom: 0.25rem;
    }}

    .episode-meta {{
      font-size: 0.8rem;
      color: #666;
      margin-bottom: 0.75rem;
    }}

    audio {{
      width: 100%;
      height: 40px;
      display: block;
    }}

    footer {{
      margin-top: 3rem;
      font-size: 0.75rem;
      color: #444;
      text-align: center;
    }}
  </style>
</head>
<body>
  <header>
    <h1>Pebble Weekend</h1>
    <p>Private feed &mdash; weekly digest from Bob</p>
  </header>

  <main>
{episode_blocks}
  </main>

  <footer>Private &mdash; not for distribution</footer>
</body>
</html>
"""

with open("${INDEX_FILE}", "w", encoding="utf-8") as f:
    f.write(html)
print("index.html regenerated.")
PYEOF

echo ""
echo "Done. Episode added: ${EPISODE_DATE} -- ${EPISODE_LABEL}"
echo "Feed path: ${FEED_FILE}"
echo "Player page: ${INDEX_FILE}"
echo ""
echo "Subscribe URL:"
echo "  ${BASE_URL}/feed.xml"
echo "Player URL:"
echo "  ${BASE_URL}/"
echo ""
echo "If running on your dev machine, deploy to prod:"
echo "  rsync -av ${FEED_DIR}/ \${PROD_HOST:-user@prod-server}:/home/docker/wallykroeker.com/public/pf/${FEED_TOKEN}/"
