'use client'

import Script from 'next/script'
import Container from '@/components/Container'

// model-viewer is a web component — declare it so JSX accepts the element
declare global {
  namespace JSX {
    interface IntrinsicElements {
      'model-viewer': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & {
        src?: string
        alt?: string
        'camera-controls'?: boolean | ''
        'auto-rotate'?: boolean | ''
        'shadow-intensity'?: string
        exposure?: string
        style?: React.CSSProperties
        'camera-orbit'?: string
        'field-of-view'?: string
      }
    }
  }
}

export default function CoinTestPage() {
  return (
    <>
      {/* model-viewer web component — loads async after page is interactive */}
      <Script
        type="module"
        src="https://ajax.googleapis.com/ajax/libs/model-viewer/3.5.0/model-viewer.min.js"
        strategy="afterInteractive"
      />

      <div className="min-h-screen bg-zinc-950">
        <Container className="py-16 md:py-24">

          {/* Header */}
          <div className="text-center mb-10">
            <p className="text-sm uppercase tracking-widest text-amber-400 mb-4 font-medium">
              CAD Tool Capability Test — 2026-07-14
            </p>
            <h1 className="text-4xl md:text-6xl font-black text-white mb-4 leading-tight">
              StillPoint Coin
            </h1>
            <p className="text-zinc-400 text-lg max-w-xl mx-auto leading-relaxed">
              Interactive 3D model — drag to orbit, scroll to zoom, pinch on mobile.
              Generated by the text-to-CAD tool (build123d on OpenCASCADE).
            </p>
          </div>

          {/* 3D Viewer */}
          <div className="max-w-2xl mx-auto mb-4 rounded-2xl overflow-hidden bg-zinc-900 border border-zinc-800">
            <model-viewer
              src="/cointest/coin.glb"
              alt="StillPoint coin — 38mm diameter with spherical worry-stone divot and STILLPOINT embossed lettering"
              camera-controls=""
              auto-rotate=""
              shadow-intensity="1.2"
              exposure="1.1"
              camera-orbit="35deg 65deg 120mm"
              field-of-view="25deg"
              style={{
                width: '100%',
                height: '480px',
                backgroundColor: 'transparent',
              }}
            />
          </div>

          <p className="text-center text-zinc-500 text-sm mb-12">
            Rub the center — that smooth bowl is the worry-stone divot. &ldquo;STILLPOINT&rdquo; arcs near the rim.
          </p>

          {/* Spec */}
          <div className="max-w-2xl mx-auto mb-10">
            <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6 md:p-8">
              <h2 className="text-white font-bold text-lg mb-4">Coin Spec</h2>
              <div className="grid grid-cols-2 md:grid-cols-3 gap-3 text-sm">
                {[
                  ['Diameter', '38mm'],
                  ['Thickness', '3.5mm'],
                  ['Rim', '0.5mm chamfer'],
                  ['Divot width', '~20mm across'],
                  ['Divot depth', '1.8mm at center'],
                  ['Divot shape', 'Spherical bowl'],
                  ['Text', 'STILLPOINT'],
                  ['Font', 'Liberation Sans Bold'],
                  ['Emboss height', '0.6mm'],
                  ['Text arc radius', '15.2mm'],
                  ['Arc span', '140°'],
                  ['Files', 'STEP + STL + 3MF + GLB'],
                ].map(([label, value]) => (
                  <div key={label} className="bg-zinc-800 rounded-lg p-3">
                    <div className="text-zinc-500 text-xs mb-1">{label}</div>
                    <div className="text-zinc-200 font-medium">{value}</div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Verdict prompts */}
          <div className="max-w-2xl mx-auto mb-10">
            <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6 md:p-8">
              <h2 className="text-white font-bold text-lg mb-4">What to evaluate</h2>
              <div className="space-y-4 text-zinc-400 text-sm leading-relaxed">
                <div className="flex gap-3">
                  <span className="text-amber-400 font-bold shrink-0">Divot</span>
                  <span>Orbit to see the concave bowl from the side — does the curve read as a satisfying thumb-hollow? Spherical cut, ~20mm across, 1.8mm deep. Should look like a shallow dish, not flat.</span>
                </div>
                <div className="flex gap-3">
                  <span className="text-amber-400 font-bold shrink-0">Text</span>
                  <span>Look at the face straight-on. &ldquo;STILLPOINT&rdquo; should arc near the outer rim in bold raised letters. Is the arc balanced? Are the letterforms readable at coin scale?</span>
                </div>
                <div className="flex gap-3">
                  <span className="text-amber-400 font-bold shrink-0">Next step</span>
                  <span>If both features look right, the .3mf is in fablab/projects/stillpoint-coin/ and ready for Snapmaker Orca → U1 prototype print. Design tweaks (divot depth, text size, arc radius) are one-line parameter edits.</span>
                </div>
              </div>
            </div>
          </div>

          <div className="max-w-2xl mx-auto text-center">
            <p className="text-zinc-600 text-sm">
              Generated 2026-07-14 · Bill (FabLab Bob) · text-to-cad v0.3.9 · build123d 0.11.1
            </p>
          </div>

        </Container>
      </div>
    </>
  )
}
