import type { Metadata } from 'next'
import Container from '@/components/Container'
import Image from 'next/image'

export const metadata: Metadata = {
  title: 'StillPoint Coin — CAD Test — wallykroeker.com',
  description: 'Capability test render: text-to-CAD tool generating a StillPoint coin with worry-stone divot and embossed lettering.',
}

export default function CoinTestPage() {
  return (
    <div className="min-h-screen bg-zinc-950">
      <Container className="py-16 md:py-24">

        {/* Header */}
        <div className="text-center mb-12">
          <p className="text-sm uppercase tracking-widest text-amber-400 mb-4 font-medium">
            CAD Tool Capability Test — 2026-07-14
          </p>
          <h1 className="text-4xl md:text-6xl font-black text-white mb-4 leading-tight">
            StillPoint Coin
          </h1>
          <p className="text-zinc-400 text-lg max-w-xl mx-auto leading-relaxed">
            These renders were generated by the text-to-CAD tool (build123d on OpenCASCADE) to test two specific features: a concave worry-stone divot and embossed arced lettering — both on the front face of a 38mm coin.
          </p>
        </div>

        {/* Renders */}
        <div className="max-w-3xl mx-auto space-y-8 mb-12">

          {/* Isometric */}
          <div className="bg-zinc-900 border border-zinc-800 rounded-2xl overflow-hidden">
            <Image
              src="/cointest/coin-iso.png"
              alt="StillPoint coin — isometric view showing the worry-stone divot and STILLPOINT text embossed around the rim"
              width={2400}
              height={1600}
              className="w-full"
              priority
            />
            <div className="px-6 py-4">
              <p className="text-zinc-300 font-medium mb-1">Isometric view</p>
              <p className="text-zinc-500 text-sm">
                Shows the coin face from a 45° angle. The spherical worry-stone divot is the smooth concave bowl in the center (~20mm across, ~1.8mm deep). &ldquo;STILLPOINT&rdquo; is embossed 0.6mm above the face, arced near the outer rim in bold Liberation Sans.
              </p>
            </div>
          </div>

          {/* Top down */}
          <div className="bg-zinc-900 border border-zinc-800 rounded-2xl overflow-hidden">
            <Image
              src="/cointest/coin-top.png"
              alt="StillPoint coin — top-down view showing the divot bowl outline and arced text"
              width={2400}
              height={1600}
              className="w-full"
            />
            <div className="px-6 py-4">
              <p className="text-zinc-300 font-medium mb-1">Top-down view</p>
              <p className="text-zinc-500 text-sm">
                Direct overhead. The concave divot boundary reads as a clear circle inside the coin face. The arced text is visible near the outer rim — the emboss reads as a subtle raised surface from this angle.
              </p>
            </div>
          </div>
        </div>

        {/* Spec */}
        <div className="max-w-3xl mx-auto mb-12">
          <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6 md:p-8">
            <h2 className="text-white font-bold text-lg mb-4">Coin Spec</h2>
            <div className="grid grid-cols-2 md:grid-cols-3 gap-4 text-sm">
              {[
                ['Diameter', '38mm'],
                ['Thickness', '3.5mm'],
                ['Rim', '0.5mm chamfer'],
                ['Divot width', '~20mm across'],
                ['Divot depth', '1.8mm at center'],
                ['Divot shape', 'Spherical bowl'],
                ['Text', 'STILLPOINT'],
                ['Font', 'Liberation Sans Bold'],
                ['Emboss height', '0.6mm'],
                ['Text placement', 'Arced, outer rim'],
                ['Files', 'STEP + STL + 3MF'],
                ['Tool', 'build123d / OpenCASCADE'],
              ].map(([label, value]) => (
                <div key={label} className="bg-zinc-800 rounded-lg p-3">
                  <div className="text-zinc-500 text-xs mb-1">{label}</div>
                  <div className="text-zinc-200 font-medium">{value}</div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Verdict */}
        <div className="max-w-3xl mx-auto mb-12">
          <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6 md:p-8">
            <h2 className="text-white font-bold text-lg mb-4">What to evaluate</h2>
            <div className="space-y-4 text-zinc-400 text-sm leading-relaxed">
              <div className="flex gap-3">
                <span className="text-amber-400 font-bold shrink-0">Divot</span>
                <span>Does the concave bowl in the center look like a satisfying thumb-hollow? The geometry is a spherical cut, so it should be smooth and evenly curved — not flat or faceted. Roughly 20mm across at the coin face surface, 1.8mm deep at dead center.</span>
              </div>
              <div className="flex gap-3">
                <span className="text-amber-400 font-bold shrink-0">Text</span>
                <span>The &ldquo;STILLPOINT&rdquo; lettering arcs near the outer rim, raised 0.6mm, in bold sans-serif. Is it readable at coin scale? Is the arc placement visually balanced? The text sits outside the divot boundary in the flat annular ring between the bowl and the chamfered rim.</span>
              </div>
              <div className="flex gap-3">
                <span className="text-amber-400 font-bold shrink-0">Next step</span>
                <span>If both features look viable, the .step file is already in fablab/projects/stillpoint-coin/ — ready for Snapmaker Orca slicing and a prototype print on the U1. From here, design iteration (text size, divot depth, font choice) is a parameter change, not a rebuild.</span>
              </div>
            </div>
          </div>
        </div>

        {/* Footer note */}
        <div className="max-w-3xl mx-auto text-center">
          <p className="text-zinc-600 text-sm">
            Generated 2026-07-14 · Bill (FabLab Bob) · text-to-cad skill v0.3.9 · build123d 0.11.1
          </p>
        </div>

      </Container>
    </div>
  )
}
